project:
  type: default
  output-dir: _site

format:
  revealjs:
    theme: simple
    css: styles.css
    transition: slide
    slide-number: true
    link-external-newwindow: true

author: "TBD"
date: "2026-02"

execute:
  echo: true
  warning: false
  message: false
