---
title: "Incorporating TFL libraries like `gtsummary` and `safetyCharts` "
output: html_document
---

```{r setup, echo = FALSE, message = FALSE, warning = FALSE}
library(dplyr)
library(purrr)
library(rlang)
library(cards)
library(gt)
options("yaml.eval.expr" = TRUE) # needs for admiral -- suggest gsm ecoystem write documentation
```

# Prepare list of data of raw-data
```{r sdtm data load}
adam <- list(
  ADVS = arrow::read_parquet(system.file("demo_gsmpharmaverse/data/ADAM/ADAM_ADVS.parquet", package = "workr"))
)
```

<details>
<summary>Show ADAM preview (first 6 rows)</summary>

```{r Show SDTM DM, echo = FALSE}
head(adam$ADVS) %>% gt()
```
</details>

## Show YAML's of cards transformations

::: {.scrollbox}
```{r Show ADVS transformation for MAP}
#| echo: false
x <- readLines(system.file("demo_gsmpharmaverse/workflows/3_ADAM_TO_ARS/table_mean_arterial_pressure.yaml", package = "workr"), warn = FALSE)
cat("```yaml\n", paste(x, collapse = "\n"), "\n```\n", sep = "")
```
:::

This workflow combines aspects of `gtsummary` and `safetyCharts` modules to demonstrate how to assemble multiple static outputs or a hybrid approach that may include shiny/web app html-based modules.

```{r ADAM Workflows, message = FALSE, warning = FALSE}
ARS_workflows <- workr::MakeWorkflowList(
  strNames = "table_mean_arterial_pressure",
  strPath = "demo_gsmpharmaverse/workflows/3_ADAM_TO_ARS/",
  strPackage = "workr"
)
ARS <- workr::RunWorkflows(lWorkflows = ARS_workflows, lData = adam )
```

```{r Save ARS datasets, eval = FALSE}
map2(ARS, names(ARS), function(x,y) arrow::write_parquet(x, paste0("demo_gsmpharmaverse/data/ARS/", y,".parquet")))
```


<details>
<summary>Show Table 1 ARS (first 6 rows)</summary>
```{r, echo = FALSE}
ARS[[1]] %>%
  gt()
```
</details>


